[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gallery-lib"
version = "0.1"
description = "Gallery Library"
requires-python = ">=3.12"
dependencies = [
    "boto3",
    "click",
    "geopy",
    "jinja2",
    "networkx",
    "numpy",
    "opencv-python",
    "pandas",
    "paramiko",
    "pillow",
    "protobuf",
    "pyparsing",
    "pytz",
    "pyyaml",
    "requests",
    "scipy",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]
exclude = [
    "cache*",
    "comfyui_gif*",
    "facefiles*",
    "gallery_lib.egg-info*",
    "html chor*",
    "imagefiles*",
    "secrets*",
    "thumbnails*",
    "utils*"
]